import { useSearchParams } from 'react-router-dom';
import '@/health.css';
const booking = 'https://cal.com/skcapital/free-financial-breakdown';
const questions = [
['Who is this for?','Founders and leaders of startups and small and medium-sized businesses, and investors seeking investment assessment or support for portfolio companies.'],
['How involved will you be?','We analyse, recommend and guide implementation alongside your existing team. Your team owns day-to-day execution. The engagement defines our involvement and the rhythm of progress reviews.'],
['Do we need a finance team?','You need people who can provide relevant information and implement agreed actions. They do not need to form a dedicated finance department; we establish responsibilities with you.'],
['How is the engagement priced?','We agree the scope, deliverables, responsibilities and fee before paid work begins. This can be a defined assessment, a focused project or ongoing management support.'],
['What happens after the first conversation?','We establish whether we can help and propose the appropriate next step. Detailed recommendations follow analysis of relevant business information within an agreed scope.'],
];
export default function BusinessHealthReview() {
const [params] = useSearchParams();
const investor = params.get('audience') === 'investor';
const subject = investor ? 'Investment assessment or portfolio support' : 'Business Health Review';
return <div className="health"><section className="wrap section review-hero"><p className="eyebrow">{investor ? 'For investors' : 'Business Health Review'}</p><h1>{investor ? 'Discuss the opportunity.' : 'Start with your business.'}<br/><em>{investor ? 'Define the questions that matter.' : 'Tell us what you want to achieve.'}</em></h1><p className="intro">{investor ? 'Talk to us about an investment assessment or support for a portfolio company. We will establish the business context and agree where analysis and guidance can help.' : 'A first conversation about your goals, current challenges and decisions ahead. Together, we will establish where analysis and guided support could make a difference.'}</p><div className="actions"><a className="primary" href={booking}>Book a conversation ↗</a><a className="secondary" href={`mailto:advisory@skcapital.co.in?subject=${encodeURIComponent(subject)}`}>Start by email</a></div></section>
<section className="signal-band"><div className="wrap"><p>Your goals.<br/><strong>The starting point.</strong></p><p>An agreed scope.<br/><strong>Clear responsibilities.</strong></p><p>Practical guidance.<br/><strong>Regular progress reviews.</strong></p></div></section>
<section className="wrap section review-grid"><div><p className="eyebrow">The first conversation</p><h2>Help us understand<br/><em>your context.</em></h2><ul className="review-list"><li>What does the business do, and what stage is it at?</li><li>What are you trying to achieve or decide?</li><li>Where are growth, costs or performance causing concern?</li><li>How is the team organised, and who would work with us?</li><li>What information is available, and where is it maintained?</li></ul></div><aside className="review-note"><p className="eyebrow">Bring your questions</p><h3>A conversation before a data request.</h3><p>You do not need to upload financial records to make contact. A high-level overview of the business and your priorities is enough to start.</p><p>For investment enquiries, include whether you are assessing an opportunity or seeking support for an existing portfolio company.</p></aside></section>
<section className="process section"><div className="wrap"><p className="eyebrow">Once the scope is agreed</p><h2>Build the picture.<br/><em>Agree the plan.</em></h2><p className="intro">Depending on the question, discovery may include revenue and income, costs and headcount, profitability and EBITDA, cash, sales channels, current plans and the systems holding this information. We agree what is relevant and how it will be shared.</p><div className="audience-grid"><article><h3>Direction for your team</h3><p className="intro">Findings, priorities and recommended actions, with responsibilities and measures of progress agreed together.</p></article><article><h3>Support as you move forward</h3><p className="intro">Where ongoing support is agreed, we review outcomes with your team and help refine the approach when results or circumstances change.</p></article></div></div></section>
<section className="wrap section"><p className="eyebrow">Working together</p><h2>A clear understanding<br/><em>before we begin.</em></h2><div className="faq">{questions.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></section><section className="wrap section closing"><h2>Bring the ambition.<br/><em>Let’s examine the path.</em></h2><a className="primary" href={booking}>Book a conversation ↗</a><a className="email" href={`mailto:advisory@skcapital.co.in?subject=${encodeURIComponent(subject)}`}>advisory@skcapital.co.in</a></section></div>;
}
