import { Link } from 'react-router-dom';
import Team from '@/sections/Team';
import '@/health.css';
const areas = [
['01','Business performance','What is working—and what is holding the business back?','Connect revenue, costs, profitability and operating performance to identify the issues that deserve attention.'],
['02','Growth & commercial strategy','Where should you focus your next rupee?','Examine pricing, customer economics and sales channels. Assess whether marketing expenditure and growth plans make commercial sense.'],
['03','Costs & resources','Are your people and spending supporting your priorities?','Understand the cost base, headcount and use of resources. Identify opportunities to improve efficiency while protecting what the business needs to grow.'],
['04','Planning & financial health','Can the business support the next move?','Use budgets, forecasts and cash analysis to assess hiring, expansion and investment decisions under different scenarios.'],
['05','Review & course correction','Is the strategy working in practice?','Compare performance with the plan, examine what has changed and guide your team on where to continue, adjust or reconsider.'],
];
const steps = [
['01','Understand','Start with your goals, business model, team and information. Agree the scope and fee before work begins.'],
['02','Diagnose','Examine commercial and financial performance to understand the causes behind the numbers.'],
['03','Prioritise','Develop a practical plan with recommended actions, responsibilities and measures of progress.'],
['04','Guide','Work alongside your team as they implement the agreed actions and navigate decisions.'],
['05','Review & adapt','Check results against expectations and recommend adjustments as the business evolves.'],
];
export default function Home() {
return <div className="health">
<section className="health-hero wrap"><div><p className="eyebrow">Management & strategy consulting</p><h1>Understand your business.<br/><em>Reduce costs.<br/>Grow revenue.</em></h1><p className="intro">See your business through a financial lens. We help founders and growing businesses identify opportunities, make better decisions and work with their teams to turn strategy into action.</p><div className="actions"><Link className="primary" to="/business-health-review">Discuss your business ↗</Link><a className="secondary" href="#services">Explore how we help ↓</a></div><p className="small">For startups and small and medium-sized businesses.</p></div>
<aside className="business-map" aria-label="Business questions we help answer"><p className="eyebrow">Start with the decision</p><div className="map-center">What should<br/>you do next?<br/><span>Bring the question. We help examine it.</span></div>{['Should we invest more in this sales channel?','Where can we reduce costs without weakening growth?','Can we afford to expand the team?','Is our current strategy delivering?'].map(q=><p className="decision-question" key={q}>{q}</p>)}<p className="small">Business context. Financial evidence. Practical direction.</p></aside></section>
<section className="signal-band"><div className="wrap"><p>Understand the drivers.<br/><strong>See what needs attention.</strong></p><p>Give your team direction.<br/><strong>Build a practical action plan.</strong></p><p>Follow the results.<br/><strong>Adjust as the business changes.</strong></p></div></section>
<section id="services" className="wrap section"><p className="eyebrow">How we help</p><div className="section-heading"><h2>Business decisions.<br/><em>A financial lens.</em></h2><p>Your goals set the agenda. We connect the commercial, operational and financial picture to help you decide where to focus and what to change.</p></div><div className="area-list">{areas.map(([n,t,q,d])=><article key={n}><span className="number">{n}</span><h3>{t}</h3><div><h4>{q}</h4><p>{d}</p></div></article>)}</div></section>
<section id="process" className="process section"><div className="wrap"><p className="eyebrow">How we work</p><h2>A plan your team can use.<br/><em>Support as it takes shape.</em></h2><p className="intro">You bring the team and knowledge of your business. We bring analysis, recommendations and guidance. Your team owns execution; we work alongside them to review progress and help resolve decisions.</p><div className="steps strategy-steps">{steps.map(([n,t,d])=><article key={n}><span className="number">{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div><Link className="secondary" to="/business-health-review">What to expect from the first conversation ↗</Link></div></section>
<section id="investors" className="wrap section"><p className="eyebrow">For investors</p><div className="section-heading"><h2>Understand the opportunity.<br/><em>Support the business.</em></h2><p>Work with SK Capital before an investment or alongside the founders of a portfolio company. We agree the questions, information and scope for each engagement.</p></div><div className="audience-grid"><article className="review-note"><h3>Investment assessment</h3><p>Examine a business through a commercial and financial lens. Bring the opportunity and the questions you need answered; we define the analysis needed to support your assessment.</p><Link className="secondary" to="/business-health-review?audience=investor">Discuss an investment assessment ↗</Link></article><article className="review-note"><h3>Portfolio-company support</h3><p>Help founders understand performance, prioritise improvements and track execution with their teams. Keep attention on the business goals and the evidence of progress.</p><Link className="secondary" to="/business-health-review?audience=investor">Discuss portfolio support ↗</Link></article></div></section>
<section className="wrap section work"><div><p className="eyebrow">The analysis behind the advice</p><h2>Make the numbers<br/><em>useful to the decision.</em></h2><p>Explore an illustrative model covering revenue, profitability, cash flow and scenarios. It shows one part of the analytical work that can inform a wider business discussion.</p><p className="small">Illustrative sample, not a client result.</p><Link className="secondary" to="/portfolio">Explore sample work ↗</Link></div><img src="/images/hero-dashboard.jpg" alt="Illustrative financial dashboard showing business performance measures" loading="lazy"/></section>
<Team/><section className="wrap section closing"><p className="eyebrow">Start with your priorities</p><h2>What would you like<br/><em>your business to achieve?</em></h2><p>Tell us where you are, what you want to improve and the decisions ahead. We will explore how we can help.</p><Link className="primary" to="/business-health-review">Discuss your business ↗</Link><a className="email" href="mailto:advisory@skcapital.co.in">advisory@skcapital.co.in</a></section></div>;
}
