import { ArrowRight } from 'lucide-react';
import Reviews from '@/components/Reviews';
import { bookingUrl, enquiryUrl, emailAddress } from '@/lib/offers';
export default function Home() {
  return <>
    <section className="py-16 sm:py-20 lg:py-24"><div className="content-width"><div className="max-w-3xl">
      <p className="eyebrow">Cash flow & profitability</p><h1 className="font-display text-5xl sm:text-6xl lg:text-7xl leading-[1.08] tracking-tight text-warm">Understand your<br className="hidden sm:block" /> business numbers.<br /><span className="text-gold">See what needs attention.</span></h1>
      <p className="text-cool text-lg leading-relaxed mt-6 max-w-2xl">Practical financial reviews for small service businesses worldwide. Understand your project margins, near-term cash and monthly performance.</p>
      <div className="flex flex-col sm:flex-row sm:items-center gap-5 mt-8"><a href={bookingUrl} target="_blank" rel="noopener noreferrer" className="button-primary">Book a free intro <ArrowRight size={16} /></a><a href="#reviews" className="text-sm text-cool hover:text-gold">Explore the reviews ↓</a></div><p className="text-xs text-cool mt-5">A free introductory conversation. Fixed-scope paid reviews. No monthly commitment.</p>
    </div></div></section>
    <Reviews />
    <section id="process" className="section-space"><div className="content-width"><p className="eyebrow">How it works</p><h2 className="section-title">A clear next step, from the start.</h2><div className="grid md:grid-cols-3 gap-10 mt-10">
      {[['01', 'Have a short intro', 'Tell us about your business and the question you want to answer. We will help you choose the right review.'], ['02', 'Agree the work', 'Confirm the scope, fee and delivery date, then send the completed input template.'], ['03', 'Understand the findings', 'Receive your review and a 15-minute walkthrough of the findings and questions to investigate.']].map(([number, title, text]) => <div key={number}><span className="font-ui text-gold text-sm">{number}</span><h3 className="font-display text-2xl mt-4 mb-3">{title}</h3><p className="text-cool text-sm leading-relaxed">{text}</p></div>)}
    </div></div></section>
    <section className="pb-16 lg:pb-24"><div className="content-width"><details className="border-y border-white/10 py-6"><summary className="cursor-pointer text-warm font-medium">Good to know before you start</summary><div className="max-w-3xl space-y-4 text-sm text-cool leading-relaxed mt-5"><p>Each review covers one business and one currency, using complete, organised information you provide. Data cleanup, bookkeeping, reconciliations and new budget preparation are outside these packages.</p><p>Findings depend on the information and assumptions supplied. These are financial management reviews, not audit, tax, legal or investment advice.</p><p>The intro is free. Analysis and written deliverables are paid work, with scope agreed separately. Delivery timing is agreed after reviewing your needs and inputs.</p><p>For your first email, a short description of your question is enough. Please do not include bank statements, customer details or other sensitive documents. We will agree what is needed and how to share it.</p></div></details></div></section>
    <section id="contact" className="pb-16 lg:pb-24"><div className="content-width"><div className="max-w-3xl"><h2 className="section-title">What would you like to understand better?</h2><p className="text-cool mt-5">Start with a free intro, or email us your question.</p><div className="flex flex-col sm:flex-row sm:items-center gap-5 mt-8"><a href={bookingUrl} target="_blank" rel="noopener noreferrer" className="button-primary">Book a free intro <ArrowRight size={16} /></a><a href={enquiryUrl('Business review enquiry')} className="text-sm text-cool hover:text-gold break-all">{emailAddress}</a></div><p className="text-xs text-cool mt-5">Email opens your email app. Nothing is sent automatically.</p></div></div></section>
  </>;
}
